const CreditNotesAdapter = {
  async list(filters = {}) {
    const qs = new URLSearchParams();
    if (filters.status) qs.set('status', filters.status);
    return API.get(`/credit-notes${qs.toString() ? '?' + qs.toString() : ''}`);
  },
  create(payload) { return API.post('/credit-notes', payload); },
  get(id) { return API.get(`/credit-notes/${id}`); },
  void(id, motivo) { return API.post(`/credit-notes/${id}/void`, { motivo }); },

  /**
   * Dual-source sync: trae las NCs del backend (PostgreSQL) y las fusiona en el
   * espejo local (window.db.creditNotes) preservando el `id` local y guardando
   * `backendId`. Mapea `providerAccountId` de vuelta al id local del proveedor.
   */
  async syncMirror() {
    const backend = await this.list();
    if (!Array.isArray(backend)) return null;
    const data = window.db ? window.db.get() : null;
    if (!data) return backend;

    const locals = data.creditNotes || [];
    const byNum = new Map(locals.map(n => [String(n.ncNumber), n]));
    const accounts = data.accounts || [];
    const accByBackend = new Map(accounts.map(a => [a.backendId, a]));

    const merged = backend.map((b) => {
      const existing = byNum.get(String(b.ncNumber));
      const prov = accByBackend.get(b.providerAccountId);
      const isBob = b.currency === 'BOB';
      const total = isBob ? (Number(b.totalAmountBob) || 0) : (Number(b.totalAmountUsd) || 0);
      const paid = isBob ? (Number(b.paidAmountBob) || 0) : (Number(b.paidAmountUsd) || 0);
      const balance = isBob ? (Number(b.balanceBob) || 0) : (Number(b.balanceUsd) || 0);
      return {
        id: existing ? existing.id : 'NC-' + Date.now() + Math.random().toString(36).substr(2, 6),
        backendId: b.id,
        ncNumber: b.ncNumber,
        providerId: prov ? prov.id : (existing ? existing.providerId : b.providerAccountId),
        providerName: prov ? prov.name : (existing ? existing.providerName : ''),
        providerNit: prov ? (prov.nit || '') : (existing ? existing.providerNit : ''),
        originDebitNoteId: b.debitNoteId || (existing ? existing.originDebitNoteId : null),
        originDebitNoteNumber: existing ? existing.originDebitNoteNumber : null,
        issueDate: existing ? existing.issueDate : '',
        concept: b.concept || (existing ? existing.concept : ''),
        currency: b.currency,
        totalAmount: total,
        paidAmount: paid,
        balance: balance,
        status: b.status || 'PENDIENTE',
        isAutoGenerated: b.isAutomatic === true || (existing ? existing.isAutoGenerated : false),
        createdById: existing ? existing.createdById : '',
        createdAt: existing ? existing.createdAt : (b.createdAt ? new Date(b.createdAt).toLocaleString() : new Date().toLocaleString()),
      };
    });

    data.creditNotes = merged;
    if (window.db && typeof window.db.save === 'function') window.db.save(data);
    return merged;
  },
};