/**
 * MARETRAVEL ERP - Módulo 4: Notas de Crédito a Proveedores (NC - Cuentas por Pagar)
 * Incluye: Visualización de NCs automáticas (originadas por ND) vs manuales y saldos.
 */

window.creditNotesModule = {
  currentStatusFilter: 'TODOS',

  init() {
    this.bindEvents();
    this.render();
  },

  bindEvents() {
    const statusFilter = document.getElementById('nc-status-filter');
    if (statusFilter) {
      statusFilter.addEventListener('change', (e) => {
        this.currentStatusFilter = e.target.value;
        this.render();
      });
    }

    const searchInput = document.getElementById('nc-search-input');
    if (searchInput) {
      searchInput.addEventListener('input', () => this.render());
    }

    const btnNew = document.getElementById('btn-new-nc');
    if (btnNew) {
      btnNew.addEventListener('click', () => this.openManualNcModal());
    }

    const form = document.getElementById('nc-manual-form');
    if (form) {
      form.addEventListener('submit', (e) => this.handleSaveManualNc(e));
    }
  },

  render() {
    const data = window.db.get();
    const notes = data.creditNotes || [];
    const search = (document.getElementById('nc-search-input')?.value || '').toLowerCase();
    const tableBody = document.getElementById('nc-table-body');
    if (!tableBody) return;

    let filtered = notes.filter(nc => {
      const matchStatus = this.currentStatusFilter === 'TODOS' || nc.status === this.currentStatusFilter;
      const matchSearch = String(nc.ncNumber).includes(search) ||
                          nc.providerName.toLowerCase().includes(search) ||
                          nc.concept.toLowerCase().includes(search) ||
                          (nc.originDebitNoteNumber && String(nc.originDebitNoteNumber).includes(search));
      return matchStatus && matchSearch;
    });

    if (filtered.length === 0) {
      tableBody.innerHTML = `
        <tr>
          <td colspan="8" style="text-align: center; padding: 24px; color: var(--text-muted);">
            No se encontraron Notas de Crédito de proveedores.
          </td>
        </tr>
      `;
      return;
    }

    tableBody.innerHTML = filtered.map(nc => {
      const statusBadge = nc.status === 'PAGADA' ? 'badge-emerald' :
                          nc.status === 'PARCIAL' ? 'badge-blue' :
                          nc.status === 'IMPAGA' ? 'badge-amber' : 'badge-rose';

      const originBadge = nc.isAutoGenerated ?
        `<span class="badge badge-indigo" title="Generada automáticamente al cerrar ND #${nc.originDebitNoteNumber}">Auto ND #${nc.originDebitNoteNumber}</span>` :
        `<span class="badge badge-slate">Manual</span>`;

      return `
        <tr>
          <td class="font-mono" style="font-weight: 700; color: var(--navy);">NC #${nc.ncNumber}</td>
          <td class="font-mono">${nc.issueDate}</td>
          <td>
            <div style="font-weight: 600;">${nc.providerName}</div>
            <div style="font-size: 0.72rem; color: var(--text-muted);">${nc.concept}</div>
          </td>
          <td>${originBadge}</td>
          <td class="font-mono" style="text-align: right; font-weight: 700;">
            ${nc.currency} ${Number(nc.totalAmount).toLocaleString('es-BO', { minimumFractionDigits: 2 })}
          </td>
          <td class="font-mono" style="text-align: right; color: #15803d; font-weight: 600;">
            ${nc.currency} ${Number(nc.paidAmount).toLocaleString('es-BO', { minimumFractionDigits: 2 })}
          </td>
          <td class="font-mono" style="text-align: right; color: #b91c1c; font-weight: 700;">
            ${nc.currency} ${Number(nc.balance).toLocaleString('es-BO', { minimumFractionDigits: 2 })}
          </td>
          <td><span class="badge ${statusBadge}">${nc.status}</span></td>
          <td style="text-align: center;">
            <div style="display: flex; gap: 4px; justify-content: center; flex-wrap: wrap;">
              <button class="btn btn-secondary btn-sm" onclick="window.reportsModule.openCorrectionModal('NC', '${nc.id}')" title="Corrección Contable">
                <i data-lucide="edit-3"></i>
              </button>
              ${nc.status !== 'ANULADA' ? `
                <button class="btn btn-danger btn-sm" onclick="window.reportsModule.openVoidModal('NC', '${nc.id}')" title="Anular NC">
                  <i data-lucide="x-circle"></i>
                </button>
              ` : ''}
            </div>
          </td>
        </tr>
      `;
    }).join('');

    if (window.lucide) window.lucide.createIcons();
  },

  openManualNcModal() {
    const form = document.getElementById('nc-manual-form');
    if (form) form.reset();

    const data = window.db.get();
    const providers = data.accounts.filter(a => a.relationType === 'PROVEEDOR' || a.relationType === 'AMBOS');
    const select = document.getElementById('nc-provider-select');
    if (select) {
      select.innerHTML = '<option value="">-- Seleccionar Proveedor --</option>' +
        providers.map(p => `<option value="${p.id}">${p.name} (${p.code})</option>`).join('');
    }

    const nextNc = (data.creditNotes.length > 0) ? Math.max(...data.creditNotes.map(c => c.ncNumber)) + 1 : 501;
    document.getElementById('nc-number-display').textContent = `NC #${nextNc}`;
    document.getElementById('nc-issue-date').value = new Date().toISOString().split('T')[0];
    document.getElementById('nc-currency').value = 'BOB';

    window.app.openModal('modal-nc-manual');
  },

  handleSaveManualNc(e) {
    e.preventDefault();
    const data = window.db.get();
    const providerId = document.getElementById('nc-provider-select').value;
    const provider = data.accounts.find(a => a.id === providerId);
    if (!provider) {
      window.app.showToast('Selecciona un proveedor válido', 'warning');
      return;
    }

    const total = parseFloat(document.getElementById('nc-total-amount').value) || 0;
    if (total <= 0) {
      window.app.showToast('El importe debe ser mayor a cero', 'warning');
      return;
    }

    const nextNc = (data.creditNotes.length > 0) ? Math.max(...data.creditNotes.map(c => c.ncNumber)) + 1 : 501;
    const newNc = {
      id: 'NC-' + Date.now(),
      ncNumber: nextNc,
      providerId: provider.id,
      providerName: provider.name,
      providerNit: provider.nit || '',
      originDebitNoteId: null,
      originDebitNoteNumber: null,
      issueDate: document.getElementById('nc-issue-date').value,
      concept: document.getElementById('nc-concept').value.trim(),
      currency: document.getElementById('nc-currency').value,
      totalAmount: total,
      paidAmount: 0.00,
      balance: total,
      status: 'IMPAGA',
      isAutoGenerated: false,
      createdById: data.currentUser.id,
      createdAt: new Date().toLocaleString()
    };

    data.creditNotes.unshift(newNc);
    window.db.save(data);
    window.app.closeModal('modal-nc-manual');
    window.app.showToast(`Nota de Crédito NC #${newNc.ncNumber} registrada correctamente`, 'success');
    this.render();
    if (window.operationsHubModule) window.operationsHubModule.render();
    if (window.app && window.app.updateDashboardKpis) window.app.updateDashboardKpis();
  },

  /**
   * Vista previa y emisión oficial para NC
   */
  printPreview(ncId) {
    if (window.debitNotesModule && typeof window.debitNotesModule.printPreview === 'function') {
      window.debitNotesModule.printPreview(ncId, 'long', 'NC');
    }
  },

  /**
   * Alias de impresión de voucher NC
   */
  printVoucher(ncId) {
    this.printPreview(ncId);
  },

  /**
   * Impresión directa sin modal de NC
   */
  directPrint(ncId) {
    if (window.debitNotesModule && typeof window.debitNotesModule.directPrint === 'function') {
      window.debitNotesModule.directPrint(ncId, 'NC');
    }
  }
};
